version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-northeast-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t codebuild:latest .
      - docker tag codebuild:latest 441185900653.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
        - docker push codebuild:latest 441185900653.dkr.ecr.ap-northeast-1.amazonaws.com/codebuild:latest
